# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc06d536ce6adca1b7e40f901bdd959c081a3a854ad3b6fb73d872bb5c2983b5d1acda54f5d04f69cd06db8307232e32e3b587ed0c9e5b976915583eba21e3bc

test:
  secret_key_base: 9e543aeef722b5b75ba4597179346a5d682b04cd52c94c8fcfcdd3427fa55bc0972e8d6ad0eabf091b2ebba151672699a03373cd388d398453c2be8b124dd8ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
